alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
name: worldcongress
region: fra
services:
- build_command: yarn workspace client build  && yarn workspace server build
  environment_slug: node-js
  github:
    branch: main
    repo: pce/worldcongress
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  name: worldcongress
  routes:
  - path: /
  run_command: yarn workspace server start:prod
  source_dir: /